Welcome to numpy tutorial

In [1]:
import numpy as np

In [2]:
myarr=np.array([[3,6,45,7]])
myarr

array([[ 3,  6, 45,  7]])

In [3]:
#For zero row and column
myarr[0]

array([ 3,  6, 45,  7])

In [4]:
#For zero and 1 column
myarr[0,1]

6

In [5]:
#for 0 row and 2 column
myarr[0,2]

45

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
type(myarr)

numpy.ndarray

In [9]:
#Change element position
myarr[0,1]=32

In [10]:
myarr

array([[ 3, 32, 45,  7]])

Array creation: Conversion from other Python structure

In [11]:
listarray = np.array([1, 2, 3, 4])
listarray2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [12]:
listarray2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray2D.dtype

dtype('int32')

In [15]:
listarray2D.shape

(3, 3)

In [16]:
zeros=np.zeros((2,5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
range=np.arange(15)

In [19]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
lspace=np.linspace(1,20,10)

In [21]:
lspace

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [22]:
emp=np.empty((4,6))

In [23]:
emp

array([[6.95288389e-310, 6.95288388e-310, 0.00000000e+000,
        0.00000000e+000, 1.40174999e-311, 4.94065646e-324],
       [0.00000000e+000, 0.00000000e+000, 4.04738577e-320,
        0.00000000e+000, 1.23022346e-321, 1.40179280e-311],
       [1.05700345e-307, 3.11525958e-307, 0.00000000e+000,
        1.40179223e-311, 1.20160711e-306, 1.69119330e-306],
       [1.02361614e-306, 5.38531554e-322, 1.78021527e-306,
        1.69119330e-306, 9.79101082e-307,             nan]])

In [24]:
x=([[1,2,3],[4,5,6],[7,8,9]])

In [25]:
ar=np.array(x)

In [26]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
ar.sum(axis=0)

array([12, 15, 18])

In [29]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [31]:
#it transpose a matrix
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [32]:
#The numpy.ndarray.flat() function is used as a 1_D iterator over N-dimensional arrays. 
#It is not a subclass of, Python’s built-in iterator object, otherwise it a numpy.flatiter instance
ar.flat

In [34]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [35]:
ar.ndim

2

In [36]:
ar.size

9

In [37]:
ar.nbytes

36

In [38]:
#argmax it give the maximum values
one=np.array([1,2,34,54,4])
one.argmax()

3

In [39]:
one.argmin()

0

In [41]:
#it arrange into min to max
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [42]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
ar.argmin()

0

In [46]:
ar.argmax()

8

In [47]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [48]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [50]:
ar.argsort(axis=0)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]], dtype=int64)